name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean verify
    - name: Deploy to Heroku
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        HEROKU_APP_NAME: "soft-eng-2020-ic"
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: |
        cat > ~/.netrc << EOF
        machine api.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_TOKEN
        machine git.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_TOKEN
        EOF
        git push --force https://git.heroku.com/$HEROKU_APP_NAME.git HEAD:master

